name = "partyserver-example-tldraw"
main = "src/index.ts"
compatibility_date = "2024-04-19"

assets = "public"

[build]
command = "esbuild client/index.tsx --bundle --format=esm --platform=browser --outdir=public/dist"
watch_dir = "client"


[[durable_objects.bindings]]
name = "Tldraw"
class_name = "Tldraw"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Tldraw"]
